### ISSUE TITLE
Difference from rusty_money

### ISSUE THREAD

**Issue by caemor** [apibillme/monies#1]
Hey,
is there anything planned to do differently than rusty_money?
Currently it looks pretty the same besides the removal of the cryptocurrencies.
I found this crate by searching on crates.io and couldn't tell the difference.

Greetings,
Caemor

**Comment by bevanhunt** [comment]
I couldn’t use rusty-money as it has a hyphen in the name. I am not sure yet how much it will diverge but I think it will quite a lot.

**Comment by caemor** [comment]
Thanks

**Comment by bnoctis** [comment]
You can run `cargo add rusty-money` or add `rusty-money = "0.4"` to `Cargo.toml`, then `use rusty_money::{Money, iso};` in your code. It's strange to clone the code then have a LICENSE file stating you are the copyright holder.
